---
- hosts: all
  roles:

  # TODO: Tell brew cask to install in /Applications

  # Configure the dock
  # - role: dock
  #   apps:
  #   - /Applications/Chrome.app
  #   - /Applications/iTunes.app
  #   - /Applications/Rdio.app
  #   - "/Applications/Adobe Photoshop Lightroom 5.app"
  #   - "/Applications/Sublime Text 2.app"
  #   - /Applications/iTerm.app
  #   folders:
  #   - path: ~/
  #   - path: ~/Downloads
  #     sort: datemodified

  # Prevent creation of .DS_Store files
  - role: cask_package
    package_name: asepsis

  # Disable the dashboard
  - role: dashboard
    disabled: YES

  # TODO: Fonts - https://github.com/caskroom/homebrew-fonts/tree/master/Casks
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-open-sans
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-open-sans-condensed

  # CLI
  ## shell tooling
  # - role: git_config
  #   git_user_name: Jess Martin
  #   git_user_email: jessmartin@gmail.com
  #   git_push_default: tracking
  #   ### TODO: configure full gitconfig
  # - role: hub
  # - role: brew_package
  #   package_name: vim
  ## languages
  # - role: brew_package
  #   package_name: node
  # - role: rbenv
  # - role: npm_package
  #   package_name: grunt
  # - role: npm_package
  #   package_name: bower
  # - role: cask_package
  #   package_name: java
  # - role: brew_package
  #   package_name: android-sdk
  ## databases
  # - role: brew_package
  #   package_name: postgres
  # - role: brew_package
  #   package_name: mongodb

  # GUI
  ## Text Editors
  # - role: cask_package
  #   package_name: atom
  # - role: cask_package
  #   package_name: nvalt
  - role: cask_package
    package_name: sublime-text
  ## Communication
  - role: cask_package
    package_name: adium
  - role: cask_package
    package_name: skype
  ## Design & Photography
  # - role: cask_package
  #   package_name: adobe-photoshop-lightroom
  - role: cask_package
    package_name: skitch
  ## System
  - role: cask_package
    package_name: alfred
  - role: cask_package
    package_name: caffeine
  - role: cask_package
    package_name: scroll-reverser
  - role: cask_package
    package_name: sizeup
  - role: cask_package
    package_name: smcfancontrol
  ### TODO: Create a separate role and bring down geektool 
  # - role: cask_package
  #   package_name: geektool
  ## Development
  # - role: cask_package
  #   package_name: codekit
  # - role: cask_package
  #   package_name: github
  - role: cask_package
    package_name: iterm2
  # - role: cask_package
  #   package_name: truecrypt
  ## Sync
  - role: cask_package
    package_name: dropbox
  ## Browsers
  - role: cask_package
    package_name: firefox
  # - role: cask_package
  #   package_name: fluid
  # - role: cask_package
  #   package_name: google-chrome
  - role: cask_package
    package_name: google-hangouts
  ## Entertainment
  # - role: cask_package
  #   package_name: handbrake
  - role: cask_package
    package_name: rdio
  - role: cask_package
    package_name: spotify
  # - role: cask_package
  #   package_name: vlc
  ## Virtualization
  # - role: cask_package
  #   package_name: vagrant
  # - role: cask_package
  #   package_name: virtualbox
  # - role: cask_package
  #   package_name: vmware-fusion
